<a href="https://colab.research.google.com/github/4RY4N-XD/PyTorch_Fundamentals/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [155]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors

In [156]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [157]:
scalar.ndim

0

In [158]:
scalar.shape

torch.Size([])

In [159]:
scalar.item() #get the python number within the tensor

7

In [160]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [161]:
vector.ndim

1

In [162]:
vector.shape

torch.Size([2])

In [163]:
#Matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [164]:
MATRIX.ndim

2

In [165]:
MATRIX.shape

torch.Size([2, 2])

In [166]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,5,6],
                        [5,6,7]]])

TENSOR


tensor([[[1, 2, 3],
         [3, 5, 6],
         [5, 6, 7]]])

In [167]:
TENSOR.ndim

3

In [168]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random Tensors

why random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [169]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.5819, 0.5271, 0.7842, 0.6483],
        [0.7495, 0.3592, 0.4002, 0.3924],
        [0.0183, 0.2070, 0.4176, 0.1270]])

In [170]:
random_tensor.ndim

2

In [171]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and ones

In [172]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [173]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [174]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [175]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [176]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten =torch.arange(start =1, end= 10, step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [177]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [178]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, #what datatype u r using(based on precision, more the bit more the precision)
                               device= None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [179]:
float_32_tensor.dtype

torch.float32

In [180]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [181]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [182]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [183]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors (tensors attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [184]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.1110, 0.6105, 0.4685, 0.2903],
        [0.9343, 0.4845, 0.2975, 0.6500],
        [0.9503, 0.9731, 0.8280, 0.7161]])

In [185]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device is on: {some_tensor.device}")

tensor([[0.1110, 0.6105, 0.4685, 0.2903],
        [0.9343, 0.4845, 0.2975, 0.6500],
        [0.9503, 0.9731, 0.8280, 0.7161]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [186]:
#Create a tensor and 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [187]:
#Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [188]:
#Substract 10
tensor -10

tensor([-9, -8, -7])

In [189]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [190]:
torch.add(tensor, 10)

tensor([11, 12, 13])

###Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must watch:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**

In [191]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [192]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [193]:
tensor @ tensor

tensor(14)

In [194]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 595 µs, sys: 825 µs, total: 1.42 ms
Wall time: 1.28 ms


In [195]:
%%time
torch.matmul(tensor, tensor) #it is faster because it bypasses the python interpreter and run directly on C++ or cuda

CPU times: user 275 µs, sys: 36 µs, total: 311 µs
Wall time: 1.66 ms


tensor(14)

###One of the most common errors in deep learning: Shape errors

In [196]:
#Shapes for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A, tensor_B) is same as torch.matmul(tensor_A, tensor_B) just a short form to write
# torch.mm(tensor_A, tensor_B)


To fix this we need to manipulate the shape of our tensors for that we use **transpose**

In [197]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [198]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Find the min, max, mean, sum, etc (tensor aggregation)

In [199]:
#Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [200]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [201]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [202]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #mean only work on float32 so we need to change

(tensor(46.), tensor(46.))

In [203]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

##Finding the positional min and max

In [204]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [205]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of target where the minimum value occurs
x.argmin()

tensor(0)

In [206]:
x[0]

tensor(1)

In [207]:
#find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [208]:
x[9]

tensor(91)

##Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [209]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [210]:
#Add an extra dimension .reshape(row, column)
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [211]:
#Change the view
z = x.view(1,9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [212]:
#Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [213]:
#Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0) #0 as (8,4) 1 as (4,8) and for dim=2 we have to take 2x2 then add another one
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [214]:
# torch.squeeze() - remove all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

#Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [215]:
#torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

#Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [216]:
# torch.permute - rearrange the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) #[height, width, color_channels]

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,0,1) #shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") #[colour_channels, height, width]

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [217]:
x_original[0,0,0] = 34324
x_original[0,0,0], x_permuted[0,0,0]

(tensor(34324.), tensor(34324.))

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [219]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [220]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [221]:
#Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [222]:
#Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [223]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [225]:
#Get all values of 0th and 1st dimensions but only 1 ans 2nd dimesion
x[:,:,1]

tensor([[2, 5, 8]])

from IPython.core.prefilter import PythonOpsChecker
## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [228]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) #warning: when converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise
array, tensor


(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [229]:
#Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [230]:
#Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [232]:
#Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([3., 3., 3., 3., 3., 3., 3.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
## Reproducibility