<a href="https://colab.research.google.com/github/4RY4N-XD/PyTorch_Fundamentals/blob/main/00_Pytorch_Fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.10.0+cpu


## Introduction to Tensors

### Creating tensors

In [2]:
#Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item() #get the python number within the tensor

7

In [6]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix

MATRIX = torch.tensor([[7,8],
                       [9,10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
MATRIX.shape

torch.Size([2, 2])

In [12]:
#Tensor
TENSOR = torch.tensor([[[1,2,3],
                        [3,5,6],
                        [5,6,7]]])

TENSOR


tensor([[[1, 2, 3],
         [3, 5, 6],
         [5, 6, 7]]])

In [13]:
TENSOR.ndim

3

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

###Random Tensors

why random Tensors?

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

In [15]:
# Create a random tensor of size (3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.6695, 0.1481, 0.2380, 0.3847],
        [0.4132, 0.1442, 0.8480, 0.4426],
        [0.6001, 0.7863, 0.5015, 0.4437]])

In [16]:
random_tensor.ndim

2

In [17]:
#Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(224,224,3)) #height, width, color channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

###Zeros and ones

In [18]:
#Create a tensor of all zeros
zeros = torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
#Create a tensor of all ones
ones = torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [21]:
ones.dtype

torch.float32

###Creating a range of tensors and tensors-like

In [22]:
#Use torch.range() and get deprecated message, use torch.arange()
one_to_ten =torch.arange(start =1, end= 10, step = 1)
one_to_ten

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
#Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0])

###Tensor Datatype

**Note:** Tensor datatype is one of the 3 big errors you'll run into with PyTorch & deep learning:

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [24]:
#Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype= None, #what datatype u r using(based on precision, more the bit more the precision)
                               device= None, #what device is your tensor on
                               requires_grad=False) #whether or not to track gradients with this tensors operations
float_32_tensor


tensor([3., 6., 9.])

In [25]:
float_32_tensor.dtype

torch.float32

In [26]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor


tensor([3., 6., 9.], dtype=torch.float16)

In [27]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [28]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [29]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

###Getting information from tensors (tensors attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`


In [30]:
#Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.8254, 0.8323, 0.7642, 0.5650],
        [0.8391, 0.5645, 0.4902, 0.8104],
        [0.0756, 0.9039, 0.7490, 0.3541]])

In [31]:
#Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device is on: {some_tensor.device}")

tensor([[0.8254, 0.8323, 0.7642, 0.5650],
        [0.8391, 0.5645, 0.4902, 0.8104],
        [0.0756, 0.9039, 0.7490, 0.3541]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [32]:
#Create a tensor and 10 to it
tensor = torch.tensor([1,2,3])
tensor + 10

tensor([11, 12, 13])

In [33]:
#Multiply tensor by 10
tensor *10

tensor([10, 20, 30])

In [34]:
#Substract 10
tensor -10

tensor([-9, -8, -7])

In [35]:
#Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [36]:
torch.add(tensor, 10)

tensor([11, 12, 13])

###Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimension** must watch:
* `(3,2) @ (3,2)` won't work
* `(2,3) @ (3,2)` will work
* `(3,2) @ (2,3)` will work
2. The resulting matrix has the shape of the **outer dimensions**

In [37]:
#Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [38]:
#Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
tensor @ tensor

tensor(14)

In [40]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 884 µs, sys: 115 µs, total: 999 µs
Wall time: 4.35 ms


In [41]:
%%time
torch.matmul(tensor, tensor) #it is faster because it bypasses the python interpreter and run directly on C++ or cuda

CPU times: user 76 µs, sys: 0 ns, total: 76 µs
Wall time: 80.3 µs


tensor(14)

###One of the most common errors in deep learning: Shape errors

In [42]:
#Shapes for the matrix multiplication
tensor_A = torch.tensor([[1,2],
                        [3,4],
                        [5,6]])

tensor_B = torch.tensor([[7,10],
                       [8,11],
                       [9,12]])

#torch.mm(tensor_A, tensor_B) is same as torch.matmul(tensor_A, tensor_B) just a short form to write
# torch.mm(tensor_A, tensor_B)


To fix this we need to manipulate the shape of our tensors for that we use **transpose**

In [43]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [44]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

###Find the min, max, mean, sum, etc (tensor aggregation)

In [55]:
#Create a tensor
x = torch.arange(1,100,10)
x, x.dtype

(tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91]), torch.int64)

In [56]:
#Find the min
torch.min(x), x.min()

(tensor(1), tensor(1))

In [57]:
#Find the max
torch.max(x), x.max()

(tensor(91), tensor(91))

In [58]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #mean only work on float32 so we need to change

(tensor(46.), tensor(46.))

In [59]:
#Find the sum
torch.sum(x), x.sum()

(tensor(460), tensor(460))

##Finding the positional min and max

In [60]:
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [61]:
#Find the position in tensor that has the minimum value with argmin() -> returns index position of target where the minimum value occurs
x.argmin()

tensor(0)

In [62]:
x[0]

tensor(1)

In [63]:
#find the position in tensor that has the maximum value with argmax()
x.argmax()

tensor(9)

In [64]:
x[9]

tensor(91)