<a href="https://colab.research.google.com/github/4RY4N-XD/PyTorch_Fundamentals/blob/main/exercise/00_pytorch_fundamentals_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [ ]:
# Import torch
import torch

random_tensor = torch.rand(7, 7)
random_tensor

# Create random tensor


tensor([[0.5059, 0.7294, 0.4191, 0.9963, 0.4387, 0.8370, 0.1089],
        [0.7714, 0.7856, 0.2394, 0.1389, 0.5849, 0.9859, 0.9925],
        [0.6322, 0.5300, 0.0833, 0.3821, 0.4293, 0.3290, 0.7891],
        [0.9341, 0.5539, 0.9382, 0.0418, 0.4033, 0.8294, 0.5324],
        [0.2107, 0.5954, 0.2622, 0.5706, 0.5365, 0.7149, 0.0077],
        [0.7685, 0.1847, 0.8907, 0.4444, 0.8212, 0.8789, 0.6540],
        [0.9313, 0.3543, 0.5254, 0.0752, 0.9851, 0.4091, 0.1617]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [ ]:
# Create another random tensor

matric_A = torch.rand(1,7)
matric_B = torch.rand(1,7)

matric_B_transpose = matric_B.T

torch.matmul(matric_A, matric_B_transpose)

# Perform matrix multiplication


tensor([[1.3140]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [ ]:
# Set manual seed
RANDOM_SEED = 0

# Create two random tensors

torch.manual_seed(RANDOM_SEED)
matric_A = torch.rand(1,7)

torch.manual_seed(RANDOM_SEED)
matric_B = torch.rand(1,7)

print(matric_A)
print(matric_B)
# Matrix multiply tensors

matrix_mul = torch.matmul(matric_A, matric_B.T)
print(matrix_mul)

tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])
tensor([[1.5985]])


### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
import torch
torch.cuda.is_available()

True

In [ ]:
# Set random seed on the GPU

RANDOM_SEED = 1234

torch.cuda.manual_seed(RANDOM_SEED)
matrix = torch.rand(1,7, device = "cuda")

print(matrix)

tensor([[0.1272, 0.8167, 0.5440, 0.6601, 0.2721, 0.9737, 0.3903]],
       device='cuda:0')



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [2]:
# Set random seed
import torch
torch.cuda.is_available()

RANDOM_SEED = 1234

torch.cuda.manual_seed(RANDOM_SEED)
matrixA = torch.rand(2,3, device = "cuda")

torch.cuda.manual_seed(RANDOM_SEED)
matrixB = torch.rand(2,3, device = "cuda")

# Check for access to GPU

# Create two random tensors on GPU

print(matrixA)
print(matrixB)

tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')



### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [3]:
# Perform matmul on tensor_A and tensor_B

matrix_mul = torch.matmul(matrixA, matrixB.T)
print(matrix_mul)


tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')


### 8. Find the maximum and minimum values of the output of 7.

In [4]:
# Find max

max = torch.max(matrix_mul)
print(max)
# Find min

min = torch.min(matrix_mul)
print(min)


tensor(1.4578, device='cuda:0')
tensor(0.8358, device='cuda:0')


### 9. Find the maximum and minimum index values of the output of 7.

In [5]:
# Find arg max

max_index = torch.argmax(matrix_mul)
print(max_index)

# Find arg min

min_index = torch.argmin(matrix_mul)
print(min_index)

tensor(3, device='cuda:0')
tensor(1, device='cuda:0')



### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [6]:
# Set seed
import torch
torch.cuda.is_available()

RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)

# Create random tensor

tensor = torch.rand(1,1,1,10)

# Remove single dimensions
tensor_reshaped = tensor.squeeze()

# Print out tensors and their shapes

print(tensor, tensor.shape)
print(tensor_reshaped, tensor_reshaped.shape)


tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
